/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_ccfddl_ccfddl_data_fetchData_result$schema = z.object({
  'ok': z.boolean(),
  'source': z.string(),
  'error': z.string(),
  'text': z.string(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-ccfddl',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-ccfddl#ccfddl.data/fetchData',
      service: 'ccfddl.data',
      namespace: 'ccfddl.data',
      method: 'fetchData',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-ccfddl/types#CcfddlFetchResult',
        schema: _deepseek_ai_dsh_ccfddl_ccfddl_data_fetchData_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/ccfddl/src/index.ts","line":63,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "服务器端数据通道:浏览器经连接 API 调用 {@link CcfddlData.fetchData}, 语料只在本进程与页面之间流动,页面无需自行访问外网。",
        "summary": "服务器端数据通道:浏览器经连接 API 调用 {@link CcfddlData.fetchData}, 语料只在本进程与页面之间流动,页面无需自行访问外网。",
        "tags": [],
        "jsDoc": "/**\n * 服务器端数据通道:浏览器经连接 API 调用 {@link CcfddlData.fetchData},\n * 语料只在本进程与页面之间流动,页面无需自行访问外网。\n */",
        "key": "ccfddl.data",
        "exportName": "CcfddlData",
        "members": [
          {
            "kind": "method",
            "name": "fetchData",
            "signature": "@Remote async fetchData(): Promise<CcfddlFetchResult>",
            "summary": "用服务器自身的网络栈拉取 ccfddl 合并语料。",
            "jsDoc": "/**\n * 用服务器自身的网络栈拉取 ccfddl 合并语料。\n * @returns 成功携带 YAML 文本;全部失败时携带各源的可读原因。\n */"
          }
        ],
        "types": [
          {
            "name": "CcfddlFetchResult",
            "declaration": "export interface CcfddlFetchResult {\n    ok: boolean;\n    source: string;\n    error: string;\n    text: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
