/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CcfddlFetchResult } from '@deepseek-ai/dsh-ccfddl/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$63636664646c2e64617461 {
    fetchData: () => Promise<RemoteResult<CcfddlFetchResult>>
  }
  interface TypertRemoteMap {
    'ccfddl.data/fetchData': () => Promise<RemoteResult<CcfddlFetchResult>>
  }
  interface TypertRemoteNamespaceMap {
    'ccfddl.data': TypertRemoteNamespace$63636664646c2e64617461
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
